'use client';
import { useState } from 'react';
import { useBusinessQuery,useBusinessAction } from '@/features/product/data';
import { Panel,LoadState } from '@/features/product/ui';
interface InvitationInfo {linked:boolean;invitation:{email:string;expiresAt:string;acceptedAt:string|null;revokedAt:string|null;deliveryStatus:string}|null}
export function MemberInvitationPanel({memberId,name,email:initialEmail}:{memberId:string;name:string;email?:string|null}){
 const path=`members/${memberId}/account-invitation`,query=useBusinessQuery<InvitationInfo>(path),action=useBusinessAction(),[email,setEmail]=useState(initialEmail||''),[review,setReview]=useState(false);const data=query.data;
 return <Panel title="Member account access"><p className="text-sm text-slate-500">Send an explicit invitation to link {name} to a verified email account. This provides access to this member’s own profile, memberships, payments and QR card. It never grants Admin access.</p><LoadState pending={query.isPending} error={query.error} retry={query.refetch}/>{data && (data.linked?<p role="status">This member has a linked account.</p>:<>{data.invitation && <div className="space-y-2 rounded-lg bg-slate-50 p-4 text-sm"><p>Invited email: {data.invitation.email}</p><p>{data.invitation.revokedAt?'Revoked':new Date(data.invitation.expiresAt)<new Date()?'Expired':'Pending'} · Delivery: {data.invitation.deliveryStatus}</p><p>Expires {data.invitation.expiresAt.slice(0,10)}</p>{!data.invitation.revokedAt && <div className="flex flex-wrap gap-2"><button disabled={action.isPending} onClick={()=>action.mutate({path:`${path}/resend`,body:{}})}>Resend member invitation</button><button disabled={action.isPending} onClick={()=>action.mutate({path:`${path}/revoke`,body:{}})}>Revoke member invitation</button></div>}{data.invitation.deliveryStatus==='FAILED' && <p role="alert">Email delivery failed. Verify email delivery configuration and resend.</p>}</div>}<form className="space-y-3" onSubmit={e=>{e.preventDefault();setReview(true);}}><label>Member sign-in email<input type="email" required maxLength={254} value={email} disabled={review || action.isPending} onChange={e=>setEmail(e.target.value)}/></label><button disabled={review || action.isPending}>Review member invitation</button></form>{review && <div className="space-y-3 rounded-lg bg-blue-50 p-4"><p>Send access to {name}’s profile to <strong>{email.trim().toLowerCase()}</strong>? Any previous unaccepted link will stop working.</p><button disabled={action.isPending} onClick={()=>action.mutate({path,body:{email}},{onSuccess:()=>setReview(false)})}>Send member invitation</button><button disabled={action.isPending} onClick={()=>setReview(false)}>Cancel</button></div>}</>)}{action.error && <p role="alert">{action.error.message}</p>}</Panel>;
}
